### PR TITLE
Recommend against using `using Foo` in package code

### PR DESCRIPTION
**Pull request by DilumAluthge**
See https://github.com/JuliaLang/julia/pull/42080 for context and motivation.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @jrevels

**Comment by jrevels** [comment]
I'm okay with this in theory but I think it might be good to let https://github.com/JuliaLang/julia/pull/42080 play out before making a recommendation

**Comment by ararslan** [comment]
I am very, extremely, vehemently against this.

**Review by ararslan — CHANGES_REQUESTED** [review]
The current recommendations have been working perfectly well for Beacon's Julia code, which all uses this style guide. I don't know why we'd suddenly change this because somebody doesn't like it.

**Comment by Moelf** [comment]
This guide wouldn't be (easily) enforceable by JuliaFormatter, right? Not sure we need double recommendation since this isn't really part of style anyway. (you can move code around to make this happen)

**Comment by ararslan** [comment]
Not sure what you mean, @Moelf; JuliaFormatter supports YASGuide. See https://domluna.github.io/JuliaFormatter.jl/stable/yas_style/. Or do you mean that this particular recommendation is not enforceable by JuliaFormatter? If the latter, I agree, and I think that is related to what Matt Bauman was saying in the linked Julia PR about tooling.

**Comment by Moelf** [comment]
>this particular recommendation is not enforceable by JuliaFormatter

yes indeed. I'm saying this particular thing feels like less like a "style guide" than, say, "there should be space around `=`".

**Pull request closed without merging**
